### ISSUE TITLE
Tried on 2.0.3.1

### ISSUE THREAD

**Issue by aljawaid** [sabitertan/opencart-whathappens#1]
Module shows on home page if I assign it to a layout but there is no data - just a blank section with the module title.

**Comment by sabitertan** [comment]
There is no default value in sql table, try add some products or comment on a product.

**Comment by aljawaid** [comment]
I tried with adding products, review and coupon :(

**Comment by sabitertan** [comment]
Can you check if there is "oc_whathappen" table created in your database.

**Comment by aljawaid** [comment]
yes it was created.  all values are null though

**Comment by sabitertan** [comment]
Can you check system/error.log If  there is any line shows error about whathappens module? I tried module on 2.0.1.1 and 2.0.3.1 both working(with default theme).

**Comment by aljawaid** [comment]
no errors in system/error.log

I will re-install it and try again
